image: ruby:3.1

variables:
  JEKYLL_ENV: production

before_script:
  - gem install jekyll jekyll-feed jekyll-theme-chirpy bundler
  - bundle install

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
